use super::*;

fn project_ship(root: &Path, path: &Path) -> Result<ShipDef, Error> {
    let design = load_design(path)?;
    project_design(root, &design)
}

/// Compile a validated in-memory design without creating a design or ship file.
pub fn project_design(root: &Path, design: &Design) -> Result<ShipDef, Error> {
    let (_, hull) = validate_design(root, &root.join(format!("{}.toml", design.id)), design.clone())?;
    let components = load_components(root)?;
    let material = material(&design.material)?;
    let engine = plant(&components, &design.engine, &design.engine_size)?;
    let power = engine.power;
    let (thrust_per_power, power_per_thrust) = apply_thrust_step(
        hull.thrust_per_power,
        hull.power_per_thrust,
        engine.thrust_step,
    );
    let (_, _, faces) = shield_install(&components, design.shields)?;
    let shields = faces.iter().copied().max().unwrap_or(0);
    let structure = plated_structure(hull.base_structure, material, design.armored);
    let (systems, _, _) = compile_systems(&components, &design.systems)?;
    let mut weapons = Vec::new();
    let mut kind_counts = BTreeMap::<String, u32>::new();
    for w in &design.weapons {
        let c = components
            .weapons
            .get(&w.component)
            .ok_or_else(|| Error::UnknownComponent(w.component.clone()))?;
        let arc = if matches!(
            w.mount.as_str(),
            "forward" | "forward_starboard" | "forward_port"
        ) {
            "forward"
        } else {
            "rear"
        };
        let count = kind_counts.entry(c.kind.clone()).or_insert(0);
        *count = count.checked_add(1).ok_or(Error::Overflow)?;
        weapons.push(WeaponDef {
            id: format!("{}_{}", c.kind, count),
            kind: c.kind.clone(),
            mount: Some(w.mount.clone()),
            arc: arc.to_string(),
            max_range: c.max_range,
            max_charge: c.max_charge,
            max_ammo: c.max_ammo,
            accuracy_bonus: c.accuracy_bonus,
            damage_bonus: c.damage_bonus,
            repeat: c.repeat,
            pierce: c.pierce,
        });
    }
    let cost = preview_design(root, design)?.cost;
    Ok(ShipDef {
        id: design.id.clone(),
        name: design.name.clone(),
        size: design.size,
        max_maneuver_actions: hull.max_maneuver_actions,
        power: u32_field("power", power)?,
        max_shield_per_facing: shields,
        max_shields: Some(faces),
        structure: u32_field("structure", structure)?,
        power_sys: hull.power_sys,
        engine_boxes: hull.engine_boxes,
        weapon_boxes: 1,
        attack_accuracy_bonus: 0,
        weapons,
        systems,
        thrust_per_power,
        power_per_thrust,
        cost,
    })
}

/// Read-only projection of a design into generated ship bytes.
pub fn render(root: &Path, path: &Path) -> Result<Vec<u8>, Error> {
    let ship = project_ship(root, path)?;
    let body = toml::to_string_pretty(&ship).map_err(|e| Error::Serialize(e.to_string()))?;
    Ok(format!("# generated by shipsim-yard\n{body}").into_bytes())
}

/// Read-only calculation of the generated ship path.
pub fn generated_path(root: &Path, path: &Path) -> Result<PathBuf, Error> {
    let design = load_design(path)?;
    Ok(root.join("data/ships").join(format!("{}.toml", design.id)))
}

/// Read-only drift check; does not create or modify output.
pub fn check(root: &Path, path: &Path) -> Result<PathBuf, Error> {
    let out = generated_path(root, path)?;
    let expected = render(root, path)?;
    let actual = fs::read(&out).map_err(|source| {
        if source.kind() == std::io::ErrorKind::NotFound {
            Error::GeneratedMissing(out.clone())
        } else {
            Error::Read {
                path: out.clone(),
                source,
            }
        }
    })?;
    if actual != expected {
        return Err(Error::GeneratedDrift(out));
    }
    Ok(out)
}

/// Read-only drift check for all yard designs.
pub fn check_all(root: &Path) -> Result<usize, Error> {
    let designs = list_designs(root)?;
    let mut checked = 0;
    for (path, design) in designs {
        if STANDARD_CLASS_IDS.contains(&design.id.as_str()) {
            check(root, &path)?;
            checked += 1;
        }
    }
    Ok(checked)
}

/// Writes a generated ship atomically after validating overwrite policy.
pub fn compile(root: &Path, path: &Path) -> Result<PathBuf, Error> {
    let out = generated_path(root, path)?;
    let body = render(root, path)?;
    fs::create_dir_all(out.parent().unwrap()).map_err(|source| Error::Read {
        path: out.clone(),
        source,
    })?;
    if out.exists() {
        if !out.is_file() {
            return Err(Error::InvalidOutput(out));
        }
        let old = fs::read_to_string(&out).map_err(|source| Error::Read {
            path: out.clone(),
            source,
        })?;
        if !old
            .lines()
            .next()
            .is_some_and(|l| l.contains("generated by shipsim-yard"))
        {
            return Err(Error::RefuseOverwrite(out));
        }
    }
    let tmp = out.with_extension("toml.tmp");
    fs::write(&tmp, body).map_err(|source| Error::Read {
        path: tmp.clone(),
        source,
    })?;
    fs::rename(&tmp, &out).map_err(|source| Error::Read {
        path: out.clone(),
        source,
    })?;
    Ok(out)
}
